<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PALEWEB [
        <!ELEMENT PALEWEB (Alunos|Disciplinas|Materias|Certificados)*>

        <!ELEMENT Alunos (Aluno)*>
        <!ELEMENT Aluno (Nome|CPFaluno|Data_Nasc|Sexo|ID_Aluno|Login|Senha)*>
        <!ELEMENT Nome (#PCDATA)>
        <!ELEMENT CPFaluno (#PCDATA)>
        <!ELEMENT Data_Nasc (#PCDATA)>
        <!ELEMENT Sexo (#PCDATA)>
        <!ELEMENT ID_Aluno (#PCDATA)>
        <!ELEMENT Login (#PCDATA)>
        <!ELEMENT Senha (#PCDATA)>

        <!ELEMENT Disciplinas (Disciplina)*>
        <!ELEMENT Disciplina (Nome_disciplina|ID_Disciplina)*>
        <!ELEMENT Nome_disciplina (#PCDATA)>
        <!ELEMENT ID_Disciplina (#PCDATA)>

        <!ELEMENT Materias (Materia)*>
        <!ELEMENT Materia (ID_Disciplina|Numero_Certificado|Link|Nome_materia|ID_Materia|Descrição)*>
        <!ELEMENT Numero_Certificado (#PCDATA)>
        <!ELEMENT Link (#PCDATA)>
        <!ELEMENT Nome_materia (#PCDATA)>
        <!ELEMENT ID_Materia (#PCDATA)>
        <!ELEMENT Descrição (#PCDATA)>

        <!ELEMENT Certificados (Certificado)*>
        <!ELEMENT Certificado (QTD_Horas|Numero_Certificado|Nome_certificado|ID_Materia)*>
        <!ELEMENT QTD_Horas (#PCDATA)>
        <!ELEMENT Nome_certificado (#PCDATA)>
        ]>

<PALEWEB>
    <Alunos>
        <Aluno>
            <Nome> Marcos Gabriel</Nome>
            <CPFaluno>3434</CPFaluno>
            <Data_Nasc>12/08/1999</Data_Nasc>
            <Sexo>M</Sexo>
            <ID_Aluno>12900</ID_Aluno>
            <Login>Marcos.lok</Login>
            <Senha>12345</Senha>
        </Aluno>
        <Aluno>
            <Nome> Angelo Gabriel</Nome>
            <CPFaluno>2424</CPFaluno>
            <Data_Nasc>14/05/2001</Data_Nasc>
            <Sexo>M</Sexo>
            <ID_Aluno>12332</ID_Aluno>
            <Login>Gabriel.Slaker</Login>
            <Senha>12345</Senha>

        </Aluno>
        <Aluno>
        <Nome> Jesus Navas</Nome>
        <CPFaluno>3333</CPFaluno>
        <Data_Nasc>14/04/2002</Data_Nasc>
        <Sexo>M</Sexo>
        <ID_Aluno>12231</ID_Aluno>
        <Login>Jesus.Navas</Login>
        <Senha>12345</Senha>
    </Aluno>
        <Aluno>
            <Nome> Pedro Vaz</Nome>
            <CPFaluno>4444</CPFaluno>
            <Data_Nasc>14/04/2005</Data_Nasc>
            <Sexo>M</Sexo>
            <ID_Aluno>12333</ID_Aluno>
            <Login>Pedor.Vaz</Login>
            <Senha>12345</Senha>
        </Aluno>
        <Aluno>
            <Nome> Carla Perez</Nome>
            <CPFaluno>5555</CPFaluno>
            <Data_Nasc>14/04/2003</Data_Nasc>
            <Sexo>F</Sexo>
            <ID_Aluno>12234</ID_Aluno>
            <Login>Carla.perez</Login>
            <Senha>12345</Senha>
        </Aluno>
        <Aluno>
            <Nome> Maria Mara</Nome>
            <CPFaluno>6666</CPFaluno>
            <Data_Nasc>14/04/2003</Data_Nasc>
            <Sexo>F</Sexo>
            <ID_Aluno>12235</ID_Aluno>
            <Login>Maria.mara</Login>
            <Senha>12345</Senha>
        </Aluno>
        <Aluno>
            <Nome> Marlos Moreno</Nome>
            <CPFaluno>7777</CPFaluno>
            <Data_Nasc>14/04/1990</Data_Nasc>
            <Sexo>M</Sexo>
            <ID_Aluno>12236</ID_Aluno>
            <Login>Marlos.Moreno</Login>
            <Senha>12345</Senha>
        </Aluno>
        <Aluno>
            <Nome> Thiago Abreu</Nome>
            <CPFaluno>8888</CPFaluno>
            <Data_Nasc>14/06/2002</Data_Nasc>
            <Sexo>M</Sexo>
            <ID_Aluno>12237</ID_Aluno>
            <Login>Thiago.abreu</Login>
            <Senha>12345</Senha>
        </Aluno>
        <Aluno>
            <Nome> Maria Ferreira</Nome>
            <CPFaluno>9999</CPFaluno>
            <Data_Nasc>14/04/2009</Data_Nasc>
            <Sexo>S</Sexo>
            <ID_Aluno>12238</ID_Aluno>
            <Login>Maria.ferreira</Login>
            <Senha>12345</Senha>
        </Aluno>
        <Aluno>
            <Nome>Fabricio Sa</Nome>
            <CPFaluno>3333</CPFaluno>
            <Data_Nasc>14/04/2006</Data_Nasc>
            <Sexo>M</Sexo>
            <ID_Aluno>12239</ID_Aluno>
            <Login>Fabricio.sa</Login>
            <Senha>12345</Senha>
        </Aluno>
    </Alunos>
    <Disciplinas>
        <Disciplina>
            <ID_Disciplina>0001</ID_Disciplina>
            <Nome_disciplina>BANCO DE DADOS</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0002</ID_Disciplina>
            <Nome_disciplina>AED II</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0003</ID_Disciplina>
            <Nome_disciplina>ICC</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0004</ID_Disciplina>
            <Nome_disciplina>POO</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0005</ID_Disciplina>
            <Nome_disciplina>MD</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0006</ID_Disciplina>
            <Nome_disciplina>IP</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0007</ID_Disciplina>
            <Nome_disciplina>Calculo Vetorial</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0008</ID_Disciplina>
            <Nome_disciplina>AED I</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0009</ID_Disciplina>
            <Nome_disciplina>JAVA</Nome_disciplina>
        </Disciplina>
        <Disciplina>
            <ID_Disciplina>0010</ID_Disciplina>
            <Nome_disciplina>LPTC</Nome_disciplina>
        </Disciplina>
    </Disciplinas>
    <Materias>
        <Materia>
            <ID_Disciplina>0001</ID_Disciplina>
            <ID_Materia>10001</ID_Materia>
            <Nome_materia>BANCO DE DADOS XML</Nome_materia>
            <Numero_Certificado>PALAWEB10001#BD</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE BANCO DE DADOS APLICADO NO XML </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0002</ID_Disciplina>
            <ID_Materia>20001</ID_Materia>
            <Nome_materia>ARVORES RUBRO NEGRA</Nome_materia>
            <Numero_Certificado>PALAWEB20001#AEDII</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE ARVORES RUBRO NEGRA </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0002</ID_Disciplina>
            <ID_Materia>20002</ID_Materia>
            <Nome_materia>ARVORES B</Nome_materia>
            <Numero_Certificado>PALAWEB20002#AEDII</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE ARVORES B</Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0004</ID_Disciplina>
            <ID_Materia>40001</ID_Materia>
            <Nome_materia>POLIMORFISMO</Nome_materia>
            <Numero_Certificado>PALAWEB40001#POO</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE POLIMORFISMO </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0004</ID_Disciplina>
            <ID_Materia>40002</ID_Materia>
            <Nome_materia>ENCAPSULAMENTO</Nome_materia>
            <Numero_Certificado>PALAWEB40002#POO</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE ENCAPSULAMENTO </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0006</ID_Disciplina>
            <ID_Materia>60001</ID_Materia>
            <Nome_materia>LAÇOS DE REPETIÇÃO</Nome_materia>
            <Numero_Certificado>PALAWEB60001#IP</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE LAÇOS DE REPETIÇÃO </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0006</ID_Disciplina>
            <ID_Materia>60002</ID_Materia>
            <Nome_materia>STRING</Nome_materia>
            <Numero_Certificado>PALAWEB60002#IP</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE STRING </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0010</ID_Disciplina>
            <ID_Materia>100001</ID_Materia>
            <Nome_materia>ARTIGO CIENTIFICO I</Nome_materia>
            <Numero_Certificado>PALAWEB100001#LPTC</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE ARTIGO CIENTIFICO I </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0010</ID_Disciplina>
            <ID_Materia>100002</ID_Materia>
            <Nome_materia>ARTIGO CIENTIFICO II</Nome_materia>
            <Numero_Certificado>PALAWEB100002#LPTC</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE ARTIGO CIENTIFICO II </Descrição>
        </Materia>
        <Materia>
            <ID_Disciplina>0010</ID_Disciplina>
            <ID_Materia>100003</ID_Materia>
            <Nome_materia>ARTIGO CIENTIFICO III</Nome_materia>
            <Numero_Certificado>PALAWEB100003#LPTC</Numero_Certificado>
            <Link>https://www.youtube.com/watch?v=Q_KTYFgvu1s</Link>
            <Descrição>MATERIA COM FINS PARA QUE ALUNO COMPRENDA O CONCEITO DE ARTIGO CIENTIFICO II </Descrição>
        </Materia>

    </Materias>
    <Certificados>
        <Certificado>
            <Numero_Certificado>PALAWEB10001#BD</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE XML</Nome_certificado>
            <ID_Materia>10001</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB20001#BD</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE ARVORE RUBRO NEGRA</Nome_certificado>
            <ID_Materia>20001</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB20002#AEDII</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE ARVORES B</Nome_certificado>
            <ID_Materia>20002</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB40001#POO</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE POLIMORFISMO</Nome_certificado>
            <ID_Materia>40001</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB40002#POO</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE ENCAPSULAMENTO</Nome_certificado>
            <ID_Materia>40002</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB60001#IP</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE LAÇOS DE REPETIÇÃO</Nome_certificado>
            <ID_Materia>60001</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB60002#IP</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE STRING</Nome_certificado>
            <ID_Materia>60002</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB100001#LPTC</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE ARTIGO CIENTIFICO I</Nome_certificado>
            <ID_Materia>100001</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB100002#LPTC</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE ARTIGO CIENTIFICO II</Nome_certificado>
            <ID_Materia>100002</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
        <Certificado>
            <Numero_Certificado>PALAWEB100003#LPTC</Numero_Certificado>
            <Nome_certificado>CERTIFICADO DE CONCLUSAO DA MATERIA DE ARTIGO CIENTIFICO III</Nome_certificado>
            <ID_Materia>100003</ID_Materia>
            <QTD_Horas>20 MINUTOS</QTD_Horas>
        </Certificado>
    </Certificados>
</PALEWEB>
